// This file is auto-generated by scripts/generate-runtime-env.js.
window.RUNTIME_ENV = {
  "FIREBASE_API_KEY": "AIzaSyDdwnrO8RKn1ER5J3pyFbr69P9GjvR7CZ8",
  "FIREBASE_AUTH_DOMAIN": "reviewresq-app.firebaseapp.com",
  "FIREBASE_PROJECT_ID": "reviewresq-app",
  "FIREBASE_STORAGE_BUCKET": "reviewresq-app.appspot.com",
  "FIREBASE_MESSAGING_SENDER_ID": "863497920392",
  "FIREBASE_APP_ID": "1:863497920392:web:ca99060b42a50711b9e43d",
  "FIREBASE_MEASUREMENT_ID": "G-G3P2BX845N",
  "GOOGLE_OAUTH_SCOPES": "https://www.googleapis.com/auth/business.manage",
  "GOOGLE_OAUTH_CLIENT_ID": "",
  "GOOGLE_OAUTH_REDIRECT_URI": ""
};
